src/apps/account/urls.py
from django.urls import path

from apps.account.pages.profile.views import (
    AccountDetailView,
    AccountEditView,
    FollowPagination,
    EditCover
)
from apps.account.pages.users.views import (
    AccountListView,
    follow_user,
    FilterUsers,
    SearchUsers,
    DownloadUsers,
)

app_name = 'account'

urlpatterns = [
    path('users/', AccountListView.as_view(), name='users'),
    path('users/download/', DownloadUsers.as_view(), name='download_users'),
    path('users/filter/', FilterUsers.as_view(), name='filter_users'),
    path('users/search/', SearchUsers.as_view(), name='search_users'),

    path('users_profile/follow_user/', follow_user, name='follow_user'),

    path('profile_features/<slug:username>/follow_pagination/',
         FollowPagination.as_view(),
         name='follow_pagination'),
    path('profile_features/edit_window/<slug:username>/',
         AccountEditView.as_view(),
         name='edit_window'),
    path('profile_features/edit_cover/<slug:username>/', EditCover.as_view(),
         name='edit_cover'),

    path('profile/<slug:username>/', AccountDetailView.as_view(),
         name='detail'),
]

src/apps/post/urls.py
from django.urls import path

from apps.post.pages.posts.views import (
    CreatePost,
    like_post,
    download_replies,
    CreteReply,
    download_posts,
    ResetPosts,
    PostListView,
    FilterPosts,
    SearchPosts,
)

app_name = 'post'

urlpatterns = [
    path('posts/', PostListView.as_view(), name='list'),
    path('posts/like/', like_post, name='like_post'),
    path('posts/create/', CreatePost.as_view(), name='create'),
    path('posts/search/', SearchPosts.as_view(), name='search_posts'),
    path('posts/filter/', FilterPosts.as_view(), name='filter_posts'),
    path('posts/download/', download_posts, name='download_posts'),
    path('posts/reset/', ResetPosts.as_view(), name='reset_posts'),
    path('posts/create_reply/', CreteReply.as_view(), name='create_reply'),
    path('posts/download_replies/', download_replies, name='download_replies'),
]

src/config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.registration.urls')),

    path('', include('apps.dashboard.urls')),
    path('', include('apps.account.urls', namespace='account')),
    path('', include('apps.post.urls', namespace='post')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

src/apps/base/templates/base/menuBurgerContent/css.html
<style>
    .menu_burger_content,
    .menu_burger_content__item-link,
    .menu_burger_content__cross {
        transition: .56s opacity;
    }

    .burger_menu_background {
        transition: .33s top;
        position: fixed;
        top: -110%;
        right: 0;
        width: 100%;
        height: 100%;
        z-index: 1000;
        background-color: #f2f2f2;
    }

    @keyframes show {
      from { opacity: 0; }
      to { opacity: 1; }
    }

    .menu_burger_content {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;

        position: fixed;
        width: 100%;
        height: 100%;
        z-index: 1001;
        padding: 20px;
        -webkit-animation: show;
        -o-animation: show;
        animation: show;
        opacity: 0;
    }

    .base_menu_links {
        padding-bottom: 160px;
    }

    .menu_burger_content__item {
        display: inline-flex;
        justify-content: center;
        width: 100%;
        font-size: 2.3rem;
        padding: 18px;
    }
    .menu_burger_content__item-link {
        transition: .2s;
        cursor: pointer;
        text-align: center;
    }
    .menu_burger_content__item-link:hover {color: #697275;}
    .menu_burger_content__item-link--selected {display: inline-block; border-bottom: 2px solid #54575b;}

    .menu_burger_content__cross {
        cursor: pointer;
        position: fixed;
        top: 9px;
        right: 15px;
        height: 38px;
        width: 38px;
        padding: 8px;
        border-radius: 50%;
    }
    .menu_burger_content__cross:hover {background-color: rgba(0, 0, 0, 0.08)}
</style>

src/apps/base/templates/base/menuBurgerContent/menuBurgerContent.html
{% load static %}
<div class="menu_burger_content no_display">
    <div class="base_menu_links">

        <div class="menu_burger_content__item">
            <span class="menu_burger_content__item-link
                      {% if menu_selected == 'dashboard' %}menu_burger_content__item-link--selected{% endif %}"

                  onclick="
                          if (Boolean(`{% if menu_selected == 'dashboard' %}true{% else %}{% endif %}`)) {
                              closeMenuBurger()
                          } else {
                              location.href=`{% url 'dashboard' %}`
                          }">
                Dashboard
            </span>
        </div>

        <div class="menu_burger_content__item">
            <span class="menu_burger_content__item-link
                      {% if menu_selected == 'posts' %}menu_burger_content__item-link--selected{% endif %}"
                  onclick="
                          if (Boolean(`{% if menu_selected == 'posts' %}true{% else %}{% endif %}`)) {
                              closeMenuBurger()
                          } else {
                              location.href=`{% url 'post:list' %}`
                          }">
                Posts
            </span>
        </div>
        <div class="menu_burger_content__item">
            <span class="menu_burger_content__item-link
                      {% if menu_selected == 'users' %}menu_burger_content__item-link--selected{% endif %}"
                  onclick="
                          if (Boolean(`{% if menu_selected == 'users' %}true{% else %}{% endif %}`)) {
                              closeMenuBurger()
                          } else {
                              location.href=`{% url 'account:users' %}`
                          }">

                Users
            </span>
        </div>
    </div>
    <div class="menu_burger_content__cross">
        <img src="{% static 'base/images/menu_burger_cross.svg' %}" alt="">
    </div>
</div>