src/apps/account/urls.py
from django.urls import path

from apps.account.pages.profile.views import (
    AccountDetailView,
    AccountEditView,
    FollowPagination,
    EditCover
)
from apps.account.pages.users.views import (
    AccountListView,
    follow_user,
    FilterUsers,
    SearchUsers,
    DownloadUsers,
)

app_name = 'account'

urlpatterns = [
    path('users/', AccountListView.as_view(), name='users'),
    path('users/download/', DownloadUsers.as_view(), name='download_users'),
    path('users/filter/', FilterUsers.as_view(), name='filter_users'),
    path('users/search/', SearchUsers.as_view(), name='search_users'),

    path('users_profile/follow_user/', follow_user, name='follow_user'),

    path('profile_features/<slug:username>/follow_pagination/',
         FollowPagination.as_view(),
         name='follow_pagination'),
    path('profile_features/edit_window/<slug:username>/',
         AccountEditView.as_view(),
         name='edit_window'),
    path('profile_features/edit_cover/<slug:username>/', EditCover.as_view(),
         name='edit_cover'),

    path('profile/<slug:username>/', AccountDetailView.as_view(),
         name='detail'),
]

src/config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.registration.urls')),

    path('', include('apps.dashboard.urls')),
    path('', include('apps.account.urls', namespace='account')),
    path('', include('apps.post.urls', namespace='post')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

src/apps/account/pages/users/views.py
import logging

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from apps.account.pages.users.mixins import UsersListView, DefaultLimitMixin, \
    FollowActionListMixin, SearchUsersMixin, FilterUsersMixin, \
    RequestLimitMixin, UsersMenuSelectedMixin, ListUsersMixin
from apps.account.services.follow.dispatcher import dispatch_follow_action
from services.pagination.pagination import PaginationMixin

User = get_user_model()
lg = logging.getLogger(__name__)


class UsersListQuery:
    queryset = (
        User.objects
        .only(
            'photo',
            'gender',
            'is_staff',
            'username',
            'description',
        )
    )


class AccountListView(
    DefaultLimitMixin,
    FollowActionListMixin,
    UsersMenuSelectedMixin,
    ListUsersMixin,
    UsersListQuery,
    UsersListView,
):
    template_name = 'account/users/users.html'


class DownloadUsers(
    FollowActionListMixin,
    SearchUsersMixin,
    FilterUsersMixin,
    PaginationMixin,
    ListUsersMixin,
    UsersListQuery,
    UsersListView
):
    template_name = 'account/users/userListGenerated/userListGenerated.html'
    paginate_by = settings.REQUEST_USER_COUNT


class SearchUsers(
    RequestLimitMixin,
    FollowActionListMixin,
    SearchUsersMixin,
    ListUsersMixin,
    UsersListQuery,
    UsersListView
):
    template_name = 'account/users/userListGenerated/userListGenerated.html'


class FilterUsers(
    RequestLimitMixin,
    FollowActionListMixin,
    FilterUsersMixin,
    ListUsersMixin,
    UsersListQuery,
    UsersListView
):
    template_name = 'account/users/userListGenerated/userListGenerated.html'


@login_required
@require_POST
def follow_user(request: WSGIRequest) -> JsonResponse:
    other_user = get_object_or_404(
        User, username=request.POST.get('username')
    )
    action = dispatch_follow_action(
        action=request.POST.get('action'),
        my_user=request.user,
        other_user=other_user
    )
    return JsonResponse({'action': action})

src/apps/base/templates/base/header/user/userMenu/css.html
<style>
    .user_menu {
        transition: .2s;
        border-radius: 3px;
        width: 120px;
        position: fixed;
        top: 45px;
        right: 0;
        background-color: #ffffff;
        color: #35383b;
        font-size: 14px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, .1), 0 8px 16px rgba(0, 0, 0, .1);
    }
    .user_menu__item {
        cursor: pointer;
        transition: .2s;
        padding: 5px 15px;
    }
    .user_menu__item:hover {background-color: rgb(236, 236, 236);}
    .menu_item__selected {
        cursor: default;
        background-color: rgb(236, 236, 236);
    }
    .user_menu__item:last-child {border-bottom: none;}
</style>

{% include 'base/header/user/userMenu/logout/css.html' %}

src/apps/base/templates/base/header/user/userMenu/js.html
<script defer>
    function openLogoutWindow() {
        const logout_window = document.querySelector('.logout_window')

        if (typeof logout_window_block !== undefined)
            logout_window_block = true

        if (logout_window) {
            show_elem(logout_window)
            hideScroll(logout_window)
        } else {
            document.body.insertAdjacentHTML(
                'afterbegin',
                `{% include 'base/header/user/userMenu/logout/logout.html' %}`
            )
            const logout_window = document.querySelector('.logout_window')
            hideScroll(logout_window)
        }
    }
</script>

{% include 'base/header/user/userMenu/logout/js.html' %}

src/apps/base/templates/base/header/user/userMenu/userMenu.html
<ul class="user_menu no_display">
    <li class="user_menu__item {% if icon_menu__selected == 'profile' %}menu_item__selected{% endif %}"
        {% if not icon_menu__selected %}onclick="location.href='{% url 'account:detail' request.user.username %}'"{% endif %}>
        Profile
    </li>
    <li class="user_menu__item logout_link" onclick="openLogoutWindow()">
        Sign out
    </li>
</ul>